POST  http://127.0.0.1:8080/api/public/centers HTTP/1.1
Content-Type: application/json

{
    "id":1,
    "name":"Center1",
    "address":"Address1",
    "city":"City1",
    "postalCode":"PostalCode1"
}